version: "3"

networks:
  app:
    driver: overlay

volumes:
  pg_data:
  minio_data:

services:
  migrate:
    image: file:0.0.1
    entrypoint: ["uv", "run", "/app/resources/commands/migrate.py"]
    networks:
      - app
    environment:
      DEBUG: "false"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_HOST: s3
      S3_PORT: 9000
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - db
  app: 
    image: file:0.0.1
    environment:
      DEBUG: "false"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: pgbouncer
      DB_PORT: 6432
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_HOST: s3
      S3_PORT: 9000
    networks:
      - app
    volumes:
      - ./resources/logs:/app/resources/logs
    depends_on:
      - db
      - s3
      - pgbouncer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 5s
        failure_action: rollback
  nginx:
    image: nginx:1.29.5-alpine
    networks:
      - app
    ports:
      - 8000:80
    volumes:
      - ./resources/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 5s
        failure_action: rollback
  db: 
    image: postgres:17.8-bookworm
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 5s
        failure_action: rollback
  s3:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - app
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  pgbouncer:
    image: "edoburu/pgbouncer:v1.24.1-p1"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      LISTEN_PORT: 6432
      AUTH_TYPE: plain
      PGBOUNCER_POOL_MODE: "transaction"
      PGBOUNCER_MAX_CLIENT_CONN: 1000
      PGBOUNCER_DEFAULT_POOL_SIZE: 30
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "6432", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 5s
        failure_action: rollback
